### ISSUE TITLE
Problem with premake5.lua?

### ISSUE THREAD

**Issue by gvanem** [shixiongfei/actor#1]
I built Actor + `test.c` using a [GNU-makefile](https://github.com/shixiongfei/actor/files/4364971/Makefile.Windows.txt). And I like it!
But trying a `premake5.exe vs2019` in the checkout dir, and a
`msbuild -p:Configuration=Release actor.sln` casues this:
```console
Project "F:\MingW32\src\misc\ShixiongFei\Actor\actor.sln" on node 1 (default targets).
F:\MingW32\src\misc\ShixiongFei\Actor\actor.sln.metaproj : error MSB4126: The specified solution configuration "Release
|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. M
SBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the defaul
t solution configuration. [F:\MingW32\src\misc\ShixiongFei\Actor\actor.sln]
```

Is there a problem with `premake5.lua` or my VisualStudio? (BTW, I'm sick of VS).

**Comment by shixiongfei** [comment]
The default project configuration is x64 instead of x86. If you really need x86, simply change x64 in premake5.lua to x86. But I haven't run it in x86 mode on VS, but I think it should work fine.

Finally, glad you like it!

**Comment by gvanem** [comment]
That worked! 
But doing `msbuild actor.sln` fails.
But doing `msbuild actor.vcxproj` works fine. I don't understand what VS is bitching about.

**Comment by shixiongfei** [comment]
Haha, I just integrated the project and updated a bit of code. If you don't mind you can try the new version
